ViecLam/ViecLam/Models/ChiaSeKinhNghiem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ViecLam.Models
{
    public class ChiaSeKinhNghiem
    {
        public int ID { set; get; }
        public string ChuDe { set; get; }
        public string NoiDung { set; get; }
        public DateTime NgayDang { set; get; }
        public string LoiViPham { set; get; }

        public int UserID  { set; get; }
        public virtual UserProfile UserProfile { set; get; }

        public virtual ICollection<Comment> Comments { set; get; }

        public int PhanThuongID { get; set; }
        public virtual PhanThuong PhanThuong { get; set; }
        
    }
}

ViecLam/ViecLam/Controllers/ChiaSeKinhNghiemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViecLam.Models;

namespace ViecLam.Controllers
{
    [Authorize]
    public class ChiaSeKinhNghiemController : Controller
    {
        private ViecLamDbContext db = new ViecLamDbContext();

        //
        // GET: /ChiaSeKinhNghiem/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var chiasekinhnghiems = db.ChiaSeKinhNghiems.Include(c => c.UserProfile);
            return View(chiasekinhnghiems.ToList());
        }

        //
        // GET: /ChiaSeKinhNghiem/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            ChiaSeKinhNghiem chiasekinhnghiem = db.ChiaSeKinhNghiems.Find(id);
            ViewData["idpost"] = id;
            if (chiasekinhnghiem == null)
            {
                return HttpNotFound();
            }
            return View(chiasekinhnghiem);
        }

        //
        // GET: /ChiaSeKinhNghiem/Create

        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /ChiaSeKinhNghiem/Create

        [HttpPost]
        public ActionResult Create(ChiaSeKinhNghiem chiasekinhnghiem)
        {
            if (ModelState.IsValid)
            {
                chiasekinhnghiem.PhanThuongID = 1;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName })
                    .Where(y => y.UserName == User.Identity.Name).Single().UserId;
                chiasekinhnghiem.UserID = userid;
                chiasekinhnghiem.NgayDang = DateTime.Now;
                db.ChiaSeKinhNghiems.Add(chiasekinhnghiem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = new SelectList(db.UserProfiles, "UserId", "UserName", chiasekinhnghiem.UserID);
            return View(chiasekinhnghiem);
        }

        //
        // GET: /ChiaSeKinhNghiem/Edit/5

        public ActionResult Edit(int id = 0)
        {
            ChiaSeKinhNghiem chiasekinhnghiem = db.ChiaSeKinhNghiems.Find(id);
            if (chiasekinhnghiem == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserId", "UserName", chiasekinhnghiem.UserID);
            return View(chiasekinhnghiem);
        }

        //
        // POST: /ChiaSeKinhNghiem/Edit/5

        [HttpPost]
        public ActionResult Edit(ChiaSeKinhNghiem chiasekinhnghiem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chiasekinhnghiem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserId", "UserName", chiasekinhnghiem.UserID);
            return View(chiasekinhnghiem);
        }

        //
        // GET: /ChiaSeKinhNghiem/Delete/5

        public ActionResult Delete(int id = 0)
        {
            ChiaSeKinhNghiem chiasekinhnghiem = db.ChiaSeKinhNghiems.Find(id);
            if (chiasekinhnghiem == null)
            {
                return HttpNotFound();
            }
            return View(chiasekinhnghiem);
        }

        //
        // POST: /ChiaSeKinhNghiem/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            ChiaSeKinhNghiem chiasekinhnghiem = db.ChiaSeKinhNghiems.Find(id);
            db.ChiaSeKinhNghiems.Remove(chiasekinhnghiem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ViecLam/ViecLam/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViecLam.Models;

namespace ViecLam.Controllers
{
    public class CommentController : Controller
    {
        private ViecLamDbContext db = new ViecLamDbContext();

        //
        // GET: /Comment/

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.ChiaSeKinhNghiem);
            return View(comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comment/Create

        public ActionResult Create()
        {
            ViewBag.ChiaSeKinhNghiemID = new SelectList(db.ChiaSeKinhNghiems, "ID", "ChuDe");
            return View();
        }

        //
        // POST: /Comment/Create

        [HttpPost]
        public ActionResult Create(Comment comment, int idpost)
        {
            if (ModelState.IsValid)
            {
                
                comment.ChiaSeKinhNghiemID = idpost;
                comment.NgayDang = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
                return PartialView("viewComment", comment);
            }

            ViewBag.ChiaSeKinhNghiemID = new SelectList(db.ChiaSeKinhNghiems, "ID", "ChuDe", comment.ChiaSeKinhNghiemID);
            return View(comment);
        }

        //
        // GET: /Comment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.ChiaSeKinhNghiemID = new SelectList(db.ChiaSeKinhNghiems, "ID", "ChuDe", comment.ChiaSeKinhNghiemID);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5

        [HttpPost]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ChiaSeKinhNghiemID = new SelectList(db.ChiaSeKinhNghiems, "ID", "ChuDe", comment.ChiaSeKinhNghiemID);
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ViecLam/ViecLam/Controllers/PhanThuongController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViecLam.Models;

namespace ViecLam.Controllers
{
    public class PhanThuongController : Controller
    {
        private ViecLamDbContext db = new ViecLamDbContext();

        //
        // GET: /PhanThuong/

        public ActionResult Index()
        {
            return View(db.PhanThuongs.ToList());
        }

        //
        // GET: /PhanThuong/Details/5

        public ActionResult Details(int id = 0)
        {
            PhanThuong phanthuong = db.PhanThuongs.Find(id);
            if (phanthuong == null)
            {
                return HttpNotFound();
            }
            return View(phanthuong);
        }

        //
        // GET: /PhanThuong/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /PhanThuong/Create

        [HttpPost]
        public ActionResult Create(PhanThuong phanthuong)
        {
            if (ModelState.IsValid)
            {
                db.PhanThuongs.Add(phanthuong);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(phanthuong);
        }

        //
        // GET: /PhanThuong/Edit/5

        public ActionResult Edit(int id = 0)
        {
            PhanThuong phanthuong = db.PhanThuongs.Find(id);
            if (phanthuong == null)
            {
                return HttpNotFound();
            }
            return View(phanthuong);
        }

        //
        // POST: /PhanThuong/Edit/5

        [HttpPost]
        public ActionResult Edit(PhanThuong phanthuong)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phanthuong).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(phanthuong);
        }

        //
        // GET: /PhanThuong/Delete/5

        public ActionResult Delete(int id = 0)
        {
            PhanThuong phanthuong = db.PhanThuongs.Find(id);
            if (phanthuong == null)
            {
                return HttpNotFound();
            }
            return View(phanthuong);
        }

        //
        // POST: /PhanThuong/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            PhanThuong phanthuong = db.PhanThuongs.Find(id);
            db.PhanThuongs.Remove(phanthuong);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ViecLam/ViecLam/Views/ChiaSeKinhNghiem/Create.cshtml
@model ViecLam.Models.ChiaSeKinhNghiem

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>ChiaSeKinhNghiem</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ChuDe)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ChuDe)
            @Html.ValidationMessageFor(model => model.ChuDe)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NoiDung)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NoiDung)
            @Html.ValidationMessageFor(model => model.NoiDung)
        </div>     

        

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ViecLam/ViecLam/Views/ChiaSeKinhNghiem/Delete.cshtml
@model ViecLam.Models.ChiaSeKinhNghiem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>ChiaSeKinhNghiem</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ChuDe)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ChuDe)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NoiDung)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NoiDung)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NgayDang)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NgayDang)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

ViecLam/ViecLam/Views/ChiaSeKinhNghiem/Details.cshtml
@model ViecLam.Models.ChiaSeKinhNghiem

@{
    ViewBag.Title = "Details";
}
<table>
    <tr>
        <th>
            Đề Tài: 
        </th>
        <td>

        </td>
        <td>
            @Html.DisplayFor(model => model.ChuDe)
        </td>
    </tr>
</table>
<fieldset>
    <legend></legend>
<table>
    <tr>
       
            
        
        <td>
           Ngày Đăng: @Html.DisplayFor(model => model.NgayDang)
        </td>
    </tr>
</table>
</fieldset>
<table>
    <tr>
        
        
            @Html.DisplayFor(model => model.NoiDung)
       
    </tr>
</table>

  
<table>
    <div class="display-field">
     <h2>Comment</h2>
   </div>
    <tr>
        <td>

<fieldset>
  
    <legend>Comment</legend>     
    <div id="result">
    @foreach (var comment in Model.Comments.OrderByDescending(x=>x.NgayDang).Take(10))
    {
        <table>
            <tr>       
    <div class="display-field">
        Ngày Đăng: @Html.DisplayFor(x => comment.NgayDang) 
    </div>   
   
    <div class="display-field">
        @Html.DisplayFor(x => comment.NoiDung)
    </div>
                   </tr>
             </table>
    }
    </div>
   
</fieldset>
            </td>
        </tr>
    </table>
<table>
     <div class="display-field">
     <h2>Nhập Comment</h2>
   </div>
    <tr>
      
        <td>
            @Html.Partial("_addComment",new ViecLam.Models.Comment(), ViewData);
        </td>
        Không đăng tải từ ngữ dung tục, vi phạm thuần phong mĩ tục Việt Nam. Không đả kích người khác.                  
        </tr>  

</table>
    

@*<fieldset>
    <legend>ChiaSeKinhNghiem</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ChuDe)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ChuDe)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NoiDung)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NoiDung)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NgayDang)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NgayDang)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

ViecLam/ViecLam/Views/ChiaSeKinhNghiem/Edit.cshtml
@model ViecLam.Models.ChiaSeKinhNghiem

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>ChiaSeKinhNghiem</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.ChuDe)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ChuDe)
            @Html.ValidationMessageFor(model => model.ChuDe)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NoiDung)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NoiDung)
            @Html.ValidationMessageFor(model => model.NoiDung)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NgayDang)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NgayDang)
            @Html.ValidationMessageFor(model => model.NgayDang)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserID, "UserProfile")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserID", String.Empty)
            @Html.ValidationMessageFor(model => model.UserID)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ViecLam/ViecLam/Views/ChiaSeKinhNghiem/Index.cshtml
@model IEnumerable<ViecLam.Models.ChiaSeKinhNghiem>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

   <p>
        @Html.ActionLink("Đăng Bài Mới", "Create") @Html.ActionLink("Hệ Thống Phần Thưởng", "Index","PhanThuong")
   </p>
<table>
    <tr>
                <td>
                    Chia Sẻ Kiến Thức
                </td>            
               
     </tr>
</table>
   <table>
    @foreach (var item in Model)
       {          
            
        <tr>
                <td>
                      @Html.RouteLink(item.ChuDe, new { Controller = "ChiaSeKinhNghiem", Action = "Details",id=item.ID }) 
                      
                </td>
                <td>

                </td>
                <td>
                    Ngày Đăng:@Html.DisplayFor(modelItem => item.NgayDang)
                </td>
        </tr>
        
        }
   </table>
 

@*<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ChuDe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoiDung)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgayDang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserProfile.UserName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ChuDe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoiDung)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayDang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>*@

ViecLam/ViecLam/Views/ChiaSeKinhNghiem/_addComment.cshtml
@model ViecLam.Models.Comment

@using (Html.BeginForm("Create", "Comment",FormMethod.Post, new {id = "my-form" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Comment</legend>

        <div class="editor-label">
            Nhập Nội Dung 
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.NoiDung)
            @Html.ValidationMessageFor(model => model.NoiDung)
        </div>    
         @Html.ValidationMessageFor(model => model.NoiDung)
    
        @Html.Hidden("idpost",ViewData["idpost"])

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<script src="~/Scripts/addComments.js"></script>