ViecLam/ViecLam/Controllers/ChiaSeKinhNghiemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViecLam.Models;

namespace ViecLam.Controllers
{
    [Authorize]
    public class ChiaSeKinhNghiemController : Controller
    {
        private ViecLamDbContext db = new ViecLamDbContext();

        //
        // GET: /ChiaSeKinhNghiem/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var chiasekinhnghiems = db.ChiaSeKinhNghiems.Include(c => c.UserProfile);
            return View(chiasekinhnghiems.ToList());
        }

        //
        // GET: /ChiaSeKinhNghiem/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            ChiaSeKinhNghiem chiasekinhnghiem = db.ChiaSeKinhNghiems.Find(id);
            ViewData["idpost"] = id;
            if (chiasekinhnghiem == null)
            {
                return HttpNotFound();
            }
            return View(chiasekinhnghiem);
        }

        //
        // GET: /ChiaSeKinhNghiem/Create

        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /ChiaSeKinhNghiem/Create

        [HttpPost]
        public ActionResult Create(ChiaSeKinhNghiem chiasekinhnghiem)
        {
            if (ModelState.IsValid)
            {
                chiasekinhnghiem.PhanThuongID = 1;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName })
                    .Where(y => y.UserName == User.Identity.Name).Single().UserId;
                chiasekinhnghiem.UserID = userid;
                chiasekinhnghiem.NgayDang = DateTime.Now;
                db.ChiaSeKinhNghiems.Add(chiasekinhnghiem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = new SelectList(db.UserProfiles, "UserId", "UserName", chiasekinhnghiem.UserID);
            return View(chiasekinhnghiem);
        }

        //
        // GET: /ChiaSeKinhNghiem/Edit/5

        public ActionResult Edit(int id = 0)
        {
            ChiaSeKinhNghiem chiasekinhnghiem = db.ChiaSeKinhNghiems.Find(id);
            if (chiasekinhnghiem == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserId", "UserName", chiasekinhnghiem.UserID);
            return View(chiasekinhnghiem);
        }

        //
        // POST: /ChiaSeKinhNghiem/Edit/5

        [HttpPost]
        public ActionResult Edit(ChiaSeKinhNghiem chiasekinhnghiem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chiasekinhnghiem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.UserProfiles, "UserId", "UserName", chiasekinhnghiem.UserID);
            return View(chiasekinhnghiem);
        }

        //
        // GET: /ChiaSeKinhNghiem/Delete/5

        public ActionResult Delete(int id = 0)
        {
            ChiaSeKinhNghiem chiasekinhnghiem = db.ChiaSeKinhNghiems.Find(id);
            if (chiasekinhnghiem == null)
            {
                return HttpNotFound();
            }
            return View(chiasekinhnghiem);
        }

        //
        // POST: /ChiaSeKinhNghiem/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            ChiaSeKinhNghiem chiasekinhnghiem = db.ChiaSeKinhNghiems.Find(id);
            db.ChiaSeKinhNghiems.Remove(chiasekinhnghiem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ViecLam/ViecLam/Controllers/TheLoaiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViecLam.Models;

namespace ViecLam.Controllers
{
    public class TheLoaiController : Controller
    {
        private ViecLamDbContext db = new ViecLamDbContext();

        //
        // GET: /TheLoai/

        public ActionResult Index()
        {
            return View(db.TheLoais.ToList());
        }

        //
        // GET: /TheLoai/Details/5

        public ActionResult Details(int id = 0)
        {
            TheLoai theloai = db.TheLoais.Find(id);
            if (theloai == null)
            {
                return HttpNotFound();
            }
            return View(theloai);
        }

        //
        // GET: /TheLoai/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /TheLoai/Create

        [HttpPost]
        public ActionResult Create(TheLoai theloai)
        {
            if (ModelState.IsValid)
            {
                db.TheLoais.Add(theloai);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(theloai);
        }

        //
        // GET: /TheLoai/Edit/5

        public ActionResult Edit(int id = 0)
        {
            TheLoai theloai = db.TheLoais.Find(id);
            if (theloai == null)
            {
                return HttpNotFound();
            }
            return View(theloai);
        }

        //
        // POST: /TheLoai/Edit/5

        [HttpPost]
        public ActionResult Edit(TheLoai theloai)
        {
            if (ModelState.IsValid)
            {
                db.Entry(theloai).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(theloai);
        }

        //
        // GET: /TheLoai/Delete/5

        public ActionResult Delete(int id = 0)
        {
            TheLoai theloai = db.TheLoais.Find(id);
            if (theloai == null)
            {
                return HttpNotFound();
            }
            return View(theloai);
        }

        //
        // POST: /TheLoai/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            TheLoai theloai = db.TheLoais.Find(id);
            db.TheLoais.Remove(theloai);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ViecLam/ViecLam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <header>
        <div class="content-wrapper">
             <div class="anhtrangchu"></div>
            @*<div class="float-left">               
                <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
            </div>*@
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Trang Chủ", "Index", "Home")</li>
                        <li>@Html.ActionLink("Việc Làm Full-Time", "Details/1", "TheLoai")</li>
                        <li>@Html.ActionLink("Việc Làm Part-Time", "Details/2", "TheLoai")</li>
                        <li>@Html.ActionLink("Chia Sẻ Kinh Nghiệm", "Index", "ChiaSeKinhNghiem")</li>
                        <li>@Html.ActionLink("Đăng Tin", "Create", "DangViecLam")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
            </div>
        </div>
    </footer>

   
    @RenderSection("scripts", required: false)
</body>
</html>